import type { Metadata } from "next";
import { Provider } from "@/components/chakra/provider"
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
         <NuqsAdapter>
          <Provider>
            <header>Header</header>
              <main>
                {children}
              </main>
            <footer> Footer</footer>
          </Provider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
